version: '3'
services:
  app:
    build:
      context: "./"
      target: "base"
    env_file:
      - .env
    command: >
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - ".:/app"
      - "bundle:/usr/local/bundle"
    environment:
      RAILS_ENV: development
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    depends_on:
      - db
    ports:
      - "3000:3000"
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - '3316:3306'

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
